apiVersion: v1
kind: Secret
metadata:
  name: online-registration-exporter-config
data:
  config.yml: YXBpOgogIHVybDogaHR0cHM6Ly9leGFtcGxlLmNvbS9hcGkvCiAgdXNlcjogbXlfdXNlcgogIHRva2VuOiBteV90b2tlbgpwbGFuczoKLSBjbHVzdGVyQQotIGNsdXN0ZXJCCi0gY2x1c3RlckMK
